# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

TEST:
  - plugin

SQ_VERSION:
  - DEV
  - LATEST_RELEASE
  - LTS

# nothing to exclude

# exclude:
#  - TEST: plugin
#    SLAVE: linux
#    SQ_VERSION: LATEST_RELEASE
